[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.install]
command = "cargo"
args = ["install", "--path", "."]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.reinstall]
serial_tasks = ["clean", "install"]

[tasks.rebuild]
serial_tasks = ["clean", "build"]
