[package]
name = "alchemist"
version = "0.1.0"
edition = "2021"
description = "program does make but better veri gud 10/9" # TODO

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
clap_complete = "4.2.0"
colored = "2.0.0"
oh_no = { version = "0.1.0", path = "../oh_no" }
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.7.4"

[features]
