[package]
name = "alchemist"
version = "0.3.0"
edition = "2021"
description = "Task runner and build tool written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
clap_complete = "4.2.0"
oh_no = { version = "0.1.0", path = "../oh_no" }
serde = { version = "1.0.144", features = ["derive"] }
simply_colorful = { version = "0.1.0", path = "../simply_colorful" }
toml = "0.7.4"

[features]
